spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  zipkin:
    base-url: http://localhost:8768
  boot:
    admin:
      client:
        url: http://localhost:8769

server:
  port: 8767


eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
