spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8768


eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
